version: '3.8'
services:
  workspace:
    image: robotnik/ros:humble-builder
    volumes:
      - type: bind
        source: ./postcreate.sh
        target: /home/robot/postcreate.sh
        read_only: true
      - type: bind
        source: ../
        target: /home/robot/robot_ws/src/vectornav
      - type: bind
        source: /dev
        target: /dev
    privileged: true
    group_add:
      - dialout
    network_mode: host
